dist: xenial

language: php

env:
  - DB=sqlite
  - DB=mysql

php:
  - 7.1
  - 7.2
  - 7.3

matrix:
  allow_failures:
    - php: 7.3

services:
  - mysql

before_install:
  - mysql -e "set global innodb_large_prefix=1;"
  - mysql -e "set global innodb_file_format='Barracuda';"
  - mysql -e "set global innodb_file_per_table=true;"
  - mysql -e "set global innodb_default_row_format='dynamic';"

before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE totp_test;'; fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then touch database/testing.sqlite; fi"
  - composer install --no-interaction --no-ansi --prefer-dist

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache/files
