<?php
namespace Tests\Unit\Models;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use App\Models\Token;
use App\Helpers\Encryption;

class TokenTest extends TestCase
{
    use RefreshDatabase;

    private static $encryptionsalt = 'lsngmym1nd';
    private static $totpsecret = '74ZHUVE5JW4Y3HKX'; // secret generated by totp provider
    private $token;

    /**
     * Prepare for testing tokens using encryption helper with known inputs
     *
     * @return void
     */
    public function setUp()
    {
        // alter env before running setup
        putenv('ENCRYPTION_SALT=' . self::$encryptionsalt);

        parent::setUp();

        session()->put('encryptionkey', Encryption::makeKey('wish somebody would'));

        $this->token = factory(Token::class)->make();
        $this->token->secret = Encryption::encrypt(self::$totpsecret);
        $this->token->save(); // for hashed id test
    }

    /**
     * Test that the model can return a decrypted secret
     *
     * @return void
     */
    public function testSecretDecryption()
    {
        $this->assertSame(self::$totpsecret, $this->token->getDecryptedSecret());
    }

    /**
     * Test that the model can return a hashed id or null if no id present
     *
     * @return void
     */
    public function testHashedId()
    {
        $this->assertNotNull($this->token->getIdHashAttribute());

        $unsavedtoken = new Token();
        $this->assertNull($unsavedtoken->getIdHashAttribute());
    }

    /**
     * Test that the model can return a valid TOTP code
     *
     * @return void
     */
    public function testTOTPCode()
    {
        $this->assertRegExp('/^([0-9]{6})$/', $this->token->getTOTPCode());
    }

    /**
     * Test that the model can return an SVG QR code without failing
     *
     * @return void
     */
    public function testQRCode()
    {
        $this->assertEquals(0, strpos($this->token->getQRCode(), '<svg'));
    }

    /**
     * Verify that an empty path is formatted to a single slash.
     *
     * @return void
     */
    public function testEmptyPath()
    {
        $this->assertSame('/', Token::formatPath(''));
    }

    /**
     * Verify that a single slash is added to the start of a string if necessary.
     *
     * @return void
     */
    public function testLeadingPath()
    {
        $this->assertSame('/Contoso/GitHub/', Token::formatPath('Contoso/GitHub/'));
    }

    /**
     * Verify that a single slash is added to the end of a string if necessary.
     *
     * @return void;
     */
    public function testTrailingPath()
    {
        $this->assertSame('/Contoso/GitHub/', Token::formatPath('/Contoso/GitHub'));
    }

    /**
     * Verify that back slashes are switched to forward slashes
     *
     * @return void
     */
    public function testWrongSlashesInPath()
    {
        $this->assertSame('/Contoso/GitHub/', Token::formatPath('\\Contoso\\GitHub\\'));
    }

    /**
     * Verify that multiple slashes are reduced down to one
     *
     * @return void
     */
    public function testMultipleSlashesInPath()
    {
        $this->assertSame('/Contoso/GitHub/', Token::formatPath('///Contoso//GitHub/'));
    }
}
